In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[3:6]

array([4, 5, 6])

In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [11]:
print(flat[::2])

[ 1  3  5  7  9 11]
